docs(migration guide): update docs for 2.0.0 preview and migration
watson-developer-cloud/go-sdk pull request #91
Opened 2020-11-09 15:14 UTC by repjarms

### Summary

This PR adds the preview information and transition guidelines for the upcoming `2.0.0` release.

2020-11-09 15:22 UTC, mediumTaj approved these changes
👍 looks good!

2020-11-09 20:39 UTC, padamstx requested changes
A few changes needed, plus a few other suggestions that should be considered.

2020-11-09 20:39 UTC, padamstx commented on Migration-V2.md
> +In the `1.x` branch of the SDK, setter methods were provided for almost all model structs for dealing with data from the service. Version `2.0.0` makes significant breaking changesin how setters are
```suggestion
In the `1.x` version of the SDK, setter methods were provided for almost all model structs for dealing with data from the service. Version `2.0.0` makes significant breaking changes in how setters are handled for these structs.
```

2020-11-09 20:39 UTC, padamstx commented on Migration-V2.md
> +Version `2.0.0` of the Go SDK now adds alternate versions to all service functions, named `{function}WithContext`. This function calls the expected service function, but accepts a `Context` as the fi
```suggestion
Version `2.0.0` of the Go SDK now includes an alternate version of each operation belonging to the service, named `<operation>WithContext`. This alternate function allows you to pass in a `context.Context` parameter while invoking the operation.  The `context.Context` parameter can be used to specify a timeout, or cancel an in-flight request.  Details about `context.Context` can be found [here](https://golang.org/pkg/context).
```

2020-11-09 20:39 UTC, padamstx commented on Migration-V2.md
> +Internally, the Go SDK uses these functions for all operations, but the regular function provides the background context as a default.
This is a little bit confusing, but tbh I think I would just remove this sentence altogether.

2020-11-09 20:39 UTC, padamstx commented on Migration-V2.md
> +All service structs now expose a function `GetEnableGzipCompression()` and `SetEnableGzipCompression(enableGzip bool)`. These methods allow you to enable `gzip` compression within the service methods
I would NOT mention these functions unless you know for a fact that watson services allow the client to send request bodies that are gzip-compressed.   This feature is typically enabled by setting the `x-gzip-compress-requests` extension in the API definition.  If that extension is set, then the service is generated such that gzip compression is enabled by default.  If it's not set, then we still generate the "enable gzip" function so the user could explicitly enable it, but it's not enabled by default.
So my recommendation is to not mention this at all.

2020-11-09 20:39 UTC, padamstx commented on Migration-V2.md
> +All service structs will now automatically retry HTTP methods in the event of an error.
This is actually not correct.   We now provide a mechanism to enable automatic retries, but they are not enabled by default.

2020-11-09 20:39 UTC, padamstx commented on Migration-V2.md
> +Optionally, you can disable retries by using the `DisableRetries()` method exposed on the service struct.
Auto retries are disabled by default.

2020-11-09 20:39 UTC, padamstx commented on Migration-V2.md
> +- In the `Message()` function, the MessageInput{}'s `Text` property is now a `*string`. This can be constructed via the `core.StringPtr("{message}")` convenience method.
FYI... the core.XXXPtr() methods are typically used for taking the address of a literal (e.g. `core.StringPtr("string literal")`) but if you have a variable in your app, then just take the address of it:
```
     var myMessage = "message text"
     newModel := &MessageInput{MessageText: &myMessage}
```

2020-11-17 17:01 UTC, repjarms commented
@padamstx I've updated the transition notes to address your comments and include your suggestions.

2020-11-17 17:08 UTC, padamstx approved these changes
LGTM

2020-11-17 18:47 UTC, merged